### ISSUE TITLE
interfacing pisugar and/or waveshare ups hat

### ISSUE THREAD

**Issue by woahotter** [woahotter/pwnhyve#2]
i need someone with a [pi sugar](https://www.tindie.com/products/pisugar/pisugar-2-battery-for-raspberry-pi-zero/) or a [waveshare ups hat](https://www.waveshare.com/ups-hat-c.htm)

i plan on putting a battery interface on the main screen, along side some other stuff

**OR A PI UPS THAT CAN BE INTERFACED WITH I2C OR SPI, THAT ISNT OBNOXIOUSLY LARGE**

**Comment by Lehoooo** [comment]
i got the pisugar2 - lmk if you need me to test anything
